import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar"; // Navbar import qilindi
import Footer from "@/components/Footer"; // Footer import qilindi

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{
          display: "flex",
          flexDirection: "column",
          minHeight: "100vh", // Sahifa ekranni to‘liq egallaydi
        }}
      >
        <Navbar /> {/* Navbar barcha sahifalarda chiqadi */}
        <main style={{ flex: 1 }}>{children}</main> {/* Sahifa kontenti */}
        <Footer /> {/* Footer har doim pastda turadi */}
      </body>
    </html>
  );
}
